# Generated by Django 5.2.16 on 2026-07-11 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_seen', models.PositiveIntegerField(default=0)),
                ('characters_correct', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('average_speed', models.FloatField(default=0.0)),
                ('training_time', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user statistics',
            },
        ),
    ]
