# Generated by Django 5.2.16 on 2026-07-11 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('key_capture', 'Key Capture'), ('multiple_choice', 'Multiple Choice'), ('listening', 'Listening')], max_length=32)),
                ('input_method', models.CharField(blank=True, max_length=32, null=True)),
                ('question', models.CharField(max_length=255)),
                ('expected_answer', models.CharField(max_length=255)),
                ('user_answer', models.CharField(max_length=255)),
                ('correct', models.BooleanField()),
                ('response_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'practice histories',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='practice_user_created_idx')],
            },
        ),
    ]
