# Generated by Django 5.2.16 on 2026-08-02 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicehistory',
            name='speed_wpm',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Wpm 5'), (10, 'Wpm 10'), (15, 'Wpm 15'), (20, 'Wpm 20'), (25, 'Wpm 25')], null=True),
        ),
        migrations.AddIndex(
            model_name='practicehistory',
            index=models.Index(fields=['speed_wpm', 'exercise_type', 'created_at'], name='practice_leaderboard_idx'),
        ),
    ]
