# Generated by Django 5.2.16 on 2026-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_backfill_practicehistory_speed_wpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicehistory',
            name='speed_wpm',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Wpm 5'), (10, 'Wpm 10'), (15, 'Wpm 15'), (20, 'Wpm 20'), (25, 'Wpm 25')]),
        ),
    ]
