# Generated by Django 5.2.16 on 2026-07-08 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='UserMorseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_wpm', models.PositiveSmallIntegerField(choices=[(5, 'Wpm 5'), (10, 'Wpm 10'), (15, 'Wpm 15'), (20, 'Wpm 20'), (30, 'Wpm 30'), (40, 'Wpm 40'), (60, 'Wpm 60')], default=20)),
                ('frequency', models.PositiveIntegerField(default=700, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2000)])),
                ('volume', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('wave_type', models.CharField(choices=[('sine', 'Sine'), ('square', 'Square'), ('triangle', 'Triangle'), ('sawtooth', 'Sawtooth')], default='sine', max_length=16)),
                ('input_key', models.CharField(default='Space', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morse_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user morse settings',
            },
        ),
    ]
