# Generated by Django 5.2.16 on 2026-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morse', '0002_seed_allowed_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorseCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=8, unique=True)),
                ('code', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('letter', 'Letter'), ('number', 'Number'), ('punctuation', 'Punctuation')], max_length=16)),
            ],
            options={
                'ordering': ('type', 'character'),
            },
        ),
    ]
